name: Build LaTeX document

on: [push]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis/latex/thesis.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: thesis.pdf
      - name: Build plain text
        uses: docker://pandoc/core:2.9
        with:
          args: "--bibliography=thesis/latex/bibliography.bib --to=plain --wrap=none --output=thesis.txt thesis/latex/thesis.tex"
      - name: Build HTML version
        uses: docker://pandoc/core:2.9
        with:
          args: "--bibliography=thesis/latex/bibliography.bib --to=html --wrap=none --output=index.html thesis/latex/thesis.tex"
      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.repository == 'janschill/cern-solid-code-investigation' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '.github,agreements,examples,meetings,notes,presentations,prototype,report,thesis/,.gitignore,.gitmodules,README.md,thesis.acn,thesis.aux,thesis.bbl,thesis.bcf,thesis.blg,thesis.fdb_latexmk,thesis.fls,thesis.glo,thesis.ist,thesis.log,thesis.out,thesis.run.xml,thesis.toc'
          publish_dir: ./
